### ISSUE TITLE
PATH problem

### ISSUE THREAD

**Issue by ponideal** [Rudd-O/ansible-qubes#13]
user@controller bin]$ ansible dom0 -m ping
dom0 | FAILED! => {
"msg": "qrun command not found in PATH"
}

To make qubes.py work and find qrun

You need to comment out this line.

in qubes.py
`  if 'transport_cmd' in kwargs:
        self.transport_cmd = kwargs['transport_cmd']
        return
    self.transport_cmd = distutils.spawn.find_executable('qrun')
    self.transport_cmd = None
    if not self.transport_cmd:
        self.transport_cmd = os.path.join(
            os.path.dirname(__file__),
            os.path.pardir,
            "bin",`
            
` #self.transport_cmd = None`

**Comment by Rudd-O** [comment]
Fixed.
