### ISSUE TITLE
[DEPRECATION WARNING]

### ISSUE THREAD

**Issue by ponideal** [Rudd-O/ansible-qubes#14]
![image](https://user-images.githubusercontent.com/59850977/164978505-c5960a37-0cac-40bb-9bb4-dd711584395c.png)

**Comment by ponideal** [comment]
[DEPRECATION WARNING]: Distribution fedora 34 on host work should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release
 will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will
 be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
work | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}

**Comment by Rudd-O** [comment]
I think this is an Ansible issue.  Our interpreter usage always uses python3.
