### ISSUE TITLE
dom0 accessibility issue with SomeVM In qubes OS 4.1

### ISSUE THREAD

**Issue by ponideal** [Rudd-O/ansible-qubes#15]
[user@controller ansible-qubes]$ qrun dom0 shell
2022-04-22 17:04:22.094 qrexec-client-vm[2278]: process_io.c:36:handle_vchan_error: Error while vchan send(handle_input stdout), exiting

journalctl -b -a
`Apr 22 17:31:19 dom0 qrexec-policy-daemon[2158]: qrexec: qubes.VMShell+: controller -> @adminvm: allowed to dom0
Apr 22 17:31:19 dom0 qrexec-policy-daemon[37787]: 2022-04-22 17:31:19.827 qrexec-client[37787]: exec.c:511:execute_parsed_qubes_rpc_command: Unknown service >
Apr 22 17:31:19 dom0 qrexec-policy-daemon[37787]: 2022-04-22 17:31:19.847 qrexec-client[37787]: qrexec-client.c:278:handle_failed_exec: failed to spawn proce>
Apr 22 17:31:19 dom0 qrexec-policy-daemon[2158]: qrexec: qubes.VMShell: controller -> dom0: error while executing: qrexec-client failed: ['/usr/lib/qubes/qre>
lines 10121-10161/10161 (END)
`

To solve this problem, you need to make the file /etc/qubes-rpc/qubes.VMShell executable

In Dom0:

`sudo chmod +x  /etc/qubes-rpc/qubes.VMShell`

**Comment by Rudd-O** [comment]
Thanks but this already ships with executable bit in Qubes 4.1.

**Comment by Rudd-O** [comment]
Oh you mean in dom0.  That is right.
