### ISSUE TITLE
Dom0 access issue with SomeVM . Ansible

### ISSUE THREAD

**Issue by ponideal** [Rudd-O/ansible-qubes#16]
`[user@controller ~]$ ansible dom0 -m ping
[WARNING]: Unhandled error in Python interpreter discovery for host dom0: the
remote end of the Qubes connection was not ready: /home/user/autoqubes/ansible-
qubes/bin/qrun dom0 python -u -i -c ' from future import print_function
import sys, os, subprocess [sys.ps](http://sys.ps/)1 = '"'"''"'"' [sys.ps](http://sys.ps/)2 = '"'"''"'"' sys.stdin
= os.fdopen(sys.stdin.fileno(), '"'"'rb'"'"', 0) if hasattr(sys.stdin,
'"'"'buffer'"'"') else sys.stdin sys.stdout = sys.stdout.buffer if
hasattr(sys.stdout, '"'"'buffer'"'"') else sys.stdout ' yielded b''
dom0 | FAILED! => {
"msg": "the remote end of the Qubes connection was not ready: /home/user/autoqubes/ansible-qubes/bin/qrun dom0 python -u -i -c '\nfrom future import print_function\nimport sys, os, subprocess\[nsys.ps](http://nsys.ps/)1 = '"'"''"'"'\[nsys.ps](http://nsys.ps/)2 = '"'"''"'"'\nsys.stdin = os.fdopen(sys.stdin.fileno(), '"'"'rb'"'"', 0) if hasattr(sys.stdin, '"'"'buffer'"'"') else sys.stdin\nsys.stdout = sys.stdout.buffer if hasattr(sys.stdout, '"'"'buffer'"'"') else sys.stdout\n' yielded b''"`

qrun and bombshell clients work it

`[user@controller ~]$ qrun dom0 whoami`
`root`
`
[user@controller ~]$ bombshell-client dom0 whoami`
`root`

**Comment by Rudd-O** [comment]
Whaddya know, you were right.  I have fixed the issue in the latest release.
