### ISSUE TITLE
4.0-rc2: Facts gathering failing

### ISSUE THREAD

**Issue by r-cheologist** [Rudd-O/ansible-qubes#7]
Hi,

With the appropriate configuration in both `dom0` and the management VM , `./bombshell-client dom0 hostname` works just fine on my `QubesOS` 4.0-rc2 system.

Executing a playbook that used to work just fine, however, I now get during `TASK [Gathering Facts]` the following error:

    TypeError: set_host_overrides() takes exactly 3 arguments (4 given)

Any clue what might be wrong?

**Comment by r-cheologist** [comment]
Is this possibly an ansible version issue?

**Comment by Rudd-O** [comment]
This is probably an Ansible issue.  Can you update to the latest templates and verify it works?
