### ISSUE TITLE
Can ansible-qubes be used in R4?

### ISSUE THREAD

**Issue by 19hundreds** [Rudd-O/ansible-qubes#8]
Hello, your ansible-qubes idea sounds **great**

Considering #7 and the [commits](https://github.com/Rudd-O/ansible-qubes/commits) I wonder if this project can be safely and easily used in R4. I'd like to try it but I don't have much time for troubleshooting

**Comment by Rudd-O** [comment]
I believe R4 and R4.1 both work correctly, as I have tested them and they work.
