### ISSUE TITLE
Qubes OS 4. Switch screen background

### ISSUE THREAD

**Issue by Qubes123** [Rudd-O/ansible-qubes#9]
how can I change the screen background of the official Qubes OS 4.? Please help me, I am new to the IT world. maybe someone knows how to copy in Qubes 4 directly to Dom0 or connect the USB stick directly to Dom0? ask for instructions with a detailed explanation. Thank you in advance !;)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Qubes123** [comment]
hm ok but can not you help me here?

**Comment by Rudd-O** [comment]
This is not a Qubes OS support forum.
